let javascriptIsFun = true;
console.log(javascriptIsFun);
console.log(typeof javascriptIsFun);
javascriptIsFun = 'YES';
console.log(typeof javascriptIsFun);
let year;
console.log(year);
console.log(typeof year);
year = 1994;
console.log(typeof year);
console.log(typeof null);